import type { RouteConfig } from '../landingCopy';

export type PdfToolId = string;

export type PdfToolMode =
    | 'metadata_strip'
    | 'comments_remove'
    | 'hidden_text_remove'
    | 'pii_scan'
    | 'form_flatten';

export interface PdfToolDefinition {
    id: PdfToolId;
    path: string;
    name: string;
    badge: string;
    targetKeyword: string;
    mode: PdfToolMode;
    headline: string;
    description: string;
    bullets: string[];
    limitations: string[];
    resultHeading: string;
    downloadPrefix?: string;
    funnelTitle: string;
    funnelBody: string;
    funnelTargets: string[];
    relatedToolIds: PdfToolId[];
    routeConfig: RouteConfig;
}

interface ClusterToolInput {
    id: PdfToolId;
    path: string;
    name: string;
    targetKeyword: string;
    headline: string;
    description: string;
    securityHero: string;
    subhead: string;
    primarySearchIntent: string;
    metaTitle: string;
    metaDescription: string;
    focusTitle: string;
    focusText: string;
    focusBullet: string;
    howThisWorks: string;
    ctaText: string;
    funnelTitle: string;
    funnelBody: string;
    funnelTargets: string[];
    relatedToolIds: PdfToolId[];
    badge?: string;
    resultHeading?: string;
    downloadPrefix?: string;
    h1?: string;
    trustSignals?: string;
}

function createMetadataTool(input: ClusterToolInput): PdfToolDefinition {
    return {
        id: input.id,
        path: input.path,
        name: input.name,
        badge: input.badge ?? 'Metadata Tool',
        targetKeyword: input.targetKeyword,
        mode: 'metadata_strip',
        headline: input.headline,
        description: input.description,
        bullets: [
            input.focusBullet,
            'Keeps the visible document layout intact.',
            'Runs entirely in your browser.',
        ],
        limitations: [
            'Metadata cleanup does not prove covered text is gone.',
            'Comments, annotations, and ghost text can still remain in the file.',
        ],
        resultHeading: input.resultHeading ?? 'Metadata cleanup summary',
        downloadPrefix: input.downloadPrefix ?? 'metadata-cleaned',
        funnelTitle: input.funnelTitle,
        funnelBody: input.funnelBody,
        funnelTargets: input.funnelTargets,
        relatedToolIds: input.relatedToolIds,
        routeConfig: {
            path: input.path,
            primarySearchIntent: input.primarySearchIntent,
            h1: input.h1 ?? input.name,
            securityHero: input.securityHero,
            subhead: input.subhead,
            items: [
                { title: input.focusTitle, text: input.focusText },
                { title: 'Preserve Layout', text: 'Keep the visible pages intact while cleaning document properties.' },
                { title: 'Local Processing', text: 'Nothing is uploaded to a server while the PDF is processed.' },
            ],
            howThisWorks: input.howThisWorks,
            trustSignals: input.trustSignals ?? 'Local Processing • No Uploads • Metadata Cleanup',
            ctaText: input.ctaText,
            metaTitle: input.metaTitle,
            metaDescription: input.metaDescription,
        },
    };
}

function createCommentsTool(input: ClusterToolInput): PdfToolDefinition {
    return {
        id: input.id,
        path: input.path,
        name: input.name,
        badge: input.badge ?? 'Markup Tool',
        targetKeyword: input.targetKeyword,
        mode: 'comments_remove',
        headline: input.headline,
        description: input.description,
        bullets: [
            input.focusBullet,
            'Works against standard PDF annotation layers used by common editors.',
            'Shows before-and-after annotation counts for verification.',
        ],
        limitations: [
            'Removing comments does not remove hidden text under black boxes.',
            'Some documents still deserve a deeper review before sharing.',
        ],
        resultHeading: input.resultHeading ?? 'Markup removal summary',
        downloadPrefix: input.downloadPrefix ?? 'comments-removed',
        funnelTitle: input.funnelTitle,
        funnelBody: input.funnelBody,
        funnelTargets: input.funnelTargets,
        relatedToolIds: input.relatedToolIds,
        routeConfig: {
            path: input.path,
            primarySearchIntent: input.primarySearchIntent,
            h1: input.h1 ?? input.name,
            securityHero: input.securityHero,
            subhead: input.subhead,
            items: [
                { title: input.focusTitle, text: input.focusText },
                { title: 'Cross-App Cleanup', text: 'Targets the annotation structures used underneath Acrobat, Preview, and similar tools.' },
                { title: 'Verification Counts', text: 'See how many annotation objects were found before and after cleanup.' },
            ],
            howThisWorks: input.howThisWorks,
            trustSignals: input.trustSignals ?? 'Local Only • Annotation Verification • Draft Cleanup',
            ctaText: input.ctaText,
            metaTitle: input.metaTitle,
            metaDescription: input.metaDescription,
        },
    };
}

function createHiddenTextTool(input: ClusterToolInput): PdfToolDefinition {
    return {
        id: input.id,
        path: input.path,
        name: input.name,
        badge: input.badge ?? 'Flattening Tool',
        targetKeyword: input.targetKeyword,
        mode: 'hidden_text_remove',
        headline: input.headline,
        description: input.description,
        bullets: [
            input.focusBullet,
            'Creates an image-based PDF that is easier to share safely.',
            'Also removes common metadata as part of the rebuild.',
        ],
        limitations: [
            'Flattening removes searchability, selectable text, and editable fields.',
            'You may still want a deeper review before sending the final file externally.',
        ],
        resultHeading: input.resultHeading ?? 'Flattened export summary',
        downloadPrefix: input.downloadPrefix ?? 'flattened',
        funnelTitle: input.funnelTitle,
        funnelBody: input.funnelBody,
        funnelTargets: input.funnelTargets,
        relatedToolIds: input.relatedToolIds,
        routeConfig: {
            path: input.path,
            primarySearchIntent: input.primarySearchIntent,
            h1: input.h1 ?? input.name,
            securityHero: input.securityHero,
            subhead: input.subhead,
            items: [
                { title: input.focusTitle, text: input.focusText },
                { title: 'Image-Based Output', text: 'Every page is rebuilt into a flattened PDF that is harder to reverse casually.' },
                { title: 'Local Processing', text: 'The conversion runs in your browser without sending the document elsewhere.' },
            ],
            howThisWorks: input.howThisWorks,
            trustSignals: input.trustSignals ?? 'Flattened Output • Local Processing • Safer Sharing',
            ctaText: input.ctaText,
            metaTitle: input.metaTitle,
            metaDescription: input.metaDescription,
        },
    };
}

function createPiiTool(input: ClusterToolInput): PdfToolDefinition {
    return {
        id: input.id,
        path: input.path,
        name: input.name,
        badge: input.badge ?? 'Scan Tool',
        targetKeyword: input.targetKeyword,
        mode: 'pii_scan',
        headline: input.headline,
        description: input.description,
        bullets: [
            input.focusBullet,
            'Looks for names, dates, metadata traces, and ghost-text style leak signals.',
            'Runs locally in your browser without uploading the file.',
        ],
        limitations: [
            'Scanner findings are a quick review, not a legal certification.',
            'Documents with serious findings may need a fuller review before sharing.',
        ],
        resultHeading: input.resultHeading ?? 'PII scan findings',
        funnelTitle: input.funnelTitle,
        funnelBody: input.funnelBody,
        funnelTargets: input.funnelTargets,
        relatedToolIds: input.relatedToolIds,
        routeConfig: {
            path: input.path,
            primarySearchIntent: input.primarySearchIntent,
            h1: input.h1 ?? input.name,
            securityHero: input.securityHero,
            subhead: input.subhead,
            items: [
                { title: input.focusTitle, text: input.focusText },
                { title: 'Local Scan', text: 'Your PDF is scanned in-browser so the contents stay on your device.' },
                { title: 'Leak Signals', text: 'The scan also looks for ghost text and metadata that can still expose sensitive data.' },
            ],
            howThisWorks: input.howThisWorks,
            trustSignals: input.trustSignals ?? 'Client-Side Scan • No Upload • Quick Review',
            ctaText: input.ctaText,
            metaTitle: input.metaTitle,
            metaDescription: input.metaDescription,
        },
    };
}

function createFormTool(input: ClusterToolInput): PdfToolDefinition {
    return {
        id: input.id,
        path: input.path,
        name: input.name,
        badge: input.badge ?? 'Form Tool',
        targetKeyword: input.targetKeyword,
        mode: 'form_flatten',
        headline: input.headline,
        description: input.description,
        bullets: [
            input.focusBullet,
            'Turns editable fields into fixed page content.',
            'Useful for application packets, contracts, and completed forms.',
        ],
        limitations: [
            'Flattening a form does not verify hidden metadata or recoverable redaction layers.',
            'Some signed or regulated workflows still require an extra review step.',
        ],
        resultHeading: input.resultHeading ?? 'Form flattening summary',
        downloadPrefix: input.downloadPrefix ?? 'form-flattened',
        funnelTitle: input.funnelTitle,
        funnelBody: input.funnelBody,
        funnelTargets: input.funnelTargets,
        relatedToolIds: input.relatedToolIds,
        routeConfig: {
            path: input.path,
            primarySearchIntent: input.primarySearchIntent,
            h1: input.h1 ?? input.name,
            securityHero: input.securityHero,
            subhead: input.subhead,
            items: [
                { title: input.focusTitle, text: input.focusText },
                { title: 'Static Output', text: 'Interactive fields are flattened so recipients cannot casually edit the filled answers.' },
                { title: 'Local Processing', text: 'The conversion happens locally in your browser.' },
            ],
            howThisWorks: input.howThisWorks,
            trustSignals: input.trustSignals ?? 'Static Output • Local Only • Document Finalization',
            ctaText: input.ctaText,
            metaTitle: input.metaTitle,
            metaDescription: input.metaDescription,
        },
    };
}

const metadataTools = [
    createMetadataTool({
        id: 'metadata-stripper',
        path: '/tools/remove-pdf-metadata',
        name: 'PDF Metadata Stripper',
        targetKeyword: 'remove hidden data from pdf free',
        headline: 'Remove author names, producer data, and hidden PDF metadata.',
        description: 'Strips common document-info fields while preserving the visible PDF pages.',
        securityHero: 'Strip common PDF properties locally in your browser.',
        subhead: 'Remove common hidden metadata from a PDF before sending it to clients, lenders, vendors, or opposing counsel.',
        primarySearchIntent: 'Remove hidden metadata from PDF',
        metaTitle: 'PDF Metadata Stripper | Remove Hidden PDF Data Free',
        metaDescription: 'Remove author, creator, producer, and other hidden PDF metadata in your browser before sharing the file.',
        focusTitle: 'Metadata Cleanup',
        focusText: 'Remove common authoring fields that reveal software, people, and workflow history.',
        focusBullet: 'Removes Title, Author, Subject, Keywords, Creator, and Producer fields.',
        howThisWorks: 'Upload a PDF, strip common metadata fields, and download the cleaned copy.',
        ctaText: 'Strip Metadata',
        funnelTitle: 'Need a deeper document review?',
        funnelBody: 'Open the PDF Auditor if you want to check the file for hidden text, annotation content, or other leftover leak signals.',
        funnelTargets: ['/auditor', '/'],
        relatedToolIds: ['comments-remover', 'hidden-text-remover', 'form-flattener'],
        badge: 'Free Utility',
        h1: 'Remove Hidden PDF Metadata for Free',
        trustSignals: 'Local Processing • No Uploads • Fast Metadata Cleanup',
        downloadPrefix: 'metadata-stripped',
    }),
    createMetadataTool({
        id: 'remove-author-from-pdf',
        path: '/tools/remove-author-from-pdf',
        name: 'Remove Author from PDF',
        targetKeyword: 'remove author from pdf',
        headline: 'Clear the author field and related document properties from a PDF.',
        description: 'Useful when a file still shows your name or someone else\'s name in its hidden properties.',
        securityHero: 'Remove author details locally before sharing the file.',
        subhead: 'Clean the author field and related PDF properties so the document no longer exposes who created or edited it.',
        primarySearchIntent: 'Remove author from PDF',
        metaTitle: 'Remove Author from PDF | Clean PDF Properties',
        metaDescription: 'Remove the author name from a PDF in your browser and clean related hidden document properties before sending the file.',
        focusTitle: 'Author Cleanup',
        focusText: 'Clear author names and nearby document properties that can reveal who created the file.',
        focusBullet: 'Targets the Author field and other nearby PDF document properties.',
        howThisWorks: 'Upload the PDF, clear the author field and related properties, then download the cleaned copy.',
        ctaText: 'Remove Author',
        funnelTitle: 'Need broader metadata cleanup?',
        funnelBody: 'Open the PDF Metadata Stripper for a broader cleanup, or continue to the PDF Auditor for a deeper document review.',
        funnelTargets: ['/tools/remove-pdf-metadata', '/auditor'],
        relatedToolIds: ['metadata-stripper', 'comments-remover', 'hidden-text-remover'],
    }),
    createMetadataTool({
        id: 'remove-pdf-producer-info',
        path: '/tools/remove-pdf-producer-info',
        name: 'Remove PDF Producer Info',
        targetKeyword: 'remove pdf producer info',
        headline: 'Remove the producer field that reveals which app generated the PDF.',
        description: 'Clean away software fingerprints such as producer information before a document leaves your control.',
        securityHero: 'Strip software fingerprints in-browser.',
        subhead: 'Remove producer information and related metadata that can reveal which application created the document.',
        primarySearchIntent: 'Remove PDF producer information',
        metaTitle: 'Remove PDF Producer Info | Clean PDF Metadata',
        metaDescription: 'Remove producer information from a PDF in your browser and clean hidden document properties before sharing.',
        focusTitle: 'Producer Cleanup',
        focusText: 'Clear the Producer field and related software fingerprints from the PDF metadata.',
        focusBullet: 'Targets producer information that can reveal which app generated the file.',
        howThisWorks: 'Upload the PDF, remove producer information, and download the cleaned version.',
        ctaText: 'Remove Producer Info',
        funnelTitle: 'Want a broader metadata cleanup?',
        funnelBody: 'Open the PDF Metadata Stripper for a broader cleanup, or continue to the PDF Auditor if you want a deeper review.',
        funnelTargets: ['/tools/remove-pdf-metadata', '/auditor'],
        relatedToolIds: ['metadata-stripper', 'comments-remover', 'hidden-text-remover'],
    }),
    createMetadataTool({
        id: 'remove-pdf-creator-metadata',
        path: '/tools/remove-pdf-creator-metadata',
        name: 'Remove PDF Creator Metadata',
        targetKeyword: 'remove pdf creator metadata',
        headline: 'Clear creator metadata and related hidden document properties.',
        description: 'Useful when the PDF still reveals which program or workflow originally created the file.',
        securityHero: 'Clean creator metadata before you send the PDF.',
        subhead: 'Remove creator metadata and related hidden properties so the document exposes less about its origin.',
        primarySearchIntent: 'Remove PDF creator metadata',
        metaTitle: 'Remove PDF Creator Metadata | Clean Hidden Properties',
        metaDescription: 'Remove PDF creator metadata in your browser and clean hidden document properties before sharing the file.',
        focusTitle: 'Creator Cleanup',
        focusText: 'Clear creator metadata that can reveal how the document was originally generated.',
        focusBullet: 'Targets creator metadata and other hidden properties tied to document origin.',
        howThisWorks: 'Upload the PDF, clear creator metadata, and download the cleaned copy.',
        ctaText: 'Remove Creator Metadata',
        funnelTitle: 'Need broader metadata cleanup?',
        funnelBody: 'Open the PDF Metadata Stripper for a broader cleanup, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/remove-pdf-metadata', '/auditor'],
        relatedToolIds: ['metadata-stripper', 'comments-remover', 'hidden-text-remover'],
    }),
    createMetadataTool({
        id: 'anonymize-pdf-before-sending',
        path: '/tools/anonymize-pdf-before-sending',
        name: 'Anonymize PDF Before Sending',
        targetKeyword: 'anonymize pdf before sending',
        headline: 'Clean common PDF properties before emailing or uploading a document.',
        description: 'A simple metadata-cleanup step for documents that are about to be shared outside your organization.',
        securityHero: 'Anonymize PDF properties locally before sending.',
        subhead: 'Remove common document properties that can reveal who created the PDF or which software touched it.',
        primarySearchIntent: 'Anonymize PDF before sending',
        metaTitle: 'Anonymize PDF Before Sending | Clean Hidden Metadata',
        metaDescription: 'Anonymize a PDF before sending it by removing common hidden document properties in your browser.',
        focusTitle: 'Sharing Cleanup',
        focusText: 'Strip common properties that can expose people, software, and workflow details before the PDF leaves your control.',
        focusBullet: 'Helps remove common authoring traces before you email or upload a PDF.',
        howThisWorks: 'Upload a PDF, clean common hidden properties, and download the anonymized copy.',
        ctaText: 'Anonymize PDF',
        funnelTitle: 'Need a broader PDF review?',
        funnelBody: 'Open the PDF Metadata Stripper for general cleanup, or continue to the PDF Auditor if you want a deeper review.',
        funnelTargets: ['/tools/remove-pdf-metadata', '/auditor'],
        relatedToolIds: ['metadata-stripper', 'comments-remover', 'hidden-text-remover'],
    }),
    createMetadataTool({
        id: 'remove-personal-info-from-pdf-properties',
        path: '/tools/remove-personal-info-from-pdf-properties',
        name: 'Remove Personal Info from PDF Properties',
        targetKeyword: 'remove personal info from pdf file properties',
        headline: 'Clear personal information stored in common PDF file properties.',
        description: 'Helpful when file properties expose names, titles, software, or other identifying details.',
        securityHero: 'Clean personal info from PDF properties locally.',
        subhead: 'Remove common personal and software details stored in PDF properties before you share the file externally.',
        primarySearchIntent: 'Remove personal information from PDF properties',
        metaTitle: 'Remove Personal Info from PDF Properties',
        metaDescription: 'Remove personal information from PDF file properties in your browser before sharing the document.',
        focusTitle: 'Property Cleanup',
        focusText: 'Clear file-property fields that can reveal names, software, or document history.',
        focusBullet: 'Targets personal information stored in common PDF property fields.',
        howThisWorks: 'Upload the PDF, clean the file-property fields, and download the updated copy.',
        ctaText: 'Clean PDF Properties',
        funnelTitle: 'Need broader metadata cleanup?',
        funnelBody: 'Open the PDF Metadata Stripper for a broader cleanup, or continue to the PDF Auditor if you want a deeper review.',
        funnelTargets: ['/tools/remove-pdf-metadata', '/auditor'],
        relatedToolIds: ['metadata-stripper', 'comments-remover', 'hidden-text-remover'],
    }),
];

const commentsTools = [
    createCommentsTool({
        id: 'comments-remover',
        path: '/tools/remove-pdf-comments',
        name: 'PDF Comments & Markup Remover',
        targetKeyword: 'remove comments from pdf free',
        headline: 'Delete PDF comments, notes, highlights, and markup layers.',
        description: 'Removes standard page annotations across tools like Adobe Acrobat and Apple Preview by clearing the underlying PDF annotation arrays.',
        securityHero: 'Clean annotation layers without uploading the document.',
        subhead: 'Delete sticky notes, highlights, free text boxes, and markup objects before you share a working draft externally.',
        primarySearchIntent: 'Remove PDF comments and markup',
        metaTitle: 'Remove Comments from PDF Free | PDF Markup Remover',
        metaDescription: 'Remove comments, notes, highlights, and markup from a PDF in your browser before sharing the file.',
        focusTitle: 'Annotation Cleanup',
        focusText: 'Remove standard page annotations such as notes, highlights, popups, and free text markup.',
        focusBullet: 'Targets standard PDF page annotations rather than vendor-specific UI labels.',
        howThisWorks: 'Upload the PDF, remove page annotations, and download the cleaned version.',
        ctaText: 'Remove Comments',
        funnelTitle: 'Want a deeper PDF review?',
        funnelBody: 'Open the PDF Auditor if you want to check the cleaned file for hidden text, metadata, names, or dates.',
        funnelTargets: ['/auditor', '/unredact'],
        relatedToolIds: ['metadata-stripper', 'hidden-text-remover', 'pii-scanner'],
        badge: 'Free Utility',
        h1: 'Remove PDF Comments & Markup Free',
    }),
    createCommentsTool({
        id: 'remove-sticky-notes-from-pdf',
        path: '/tools/remove-sticky-notes-from-pdf',
        name: 'Remove Sticky Notes from PDF',
        targetKeyword: 'remove sticky notes from pdf',
        headline: 'Delete sticky notes and note popups from a PDF before sharing it.',
        description: 'Useful for review drafts that still contain comment balloons, note icons, or popup replies.',
        securityHero: 'Clear sticky notes locally before sending the PDF.',
        subhead: 'Remove sticky notes, note popups, and attached comment text from a PDF draft before you share it externally.',
        primarySearchIntent: 'Remove sticky notes from PDF',
        metaTitle: 'Remove Sticky Notes from PDF | Clean Comment Drafts',
        metaDescription: 'Remove sticky notes and note popups from a PDF in your browser before sending a draft or final copy.',
        focusTitle: 'Sticky Note Cleanup',
        focusText: 'Targets note annotations and related popups that often remain in reviewed PDFs.',
        focusBullet: 'Removes sticky notes and related annotation popups from the document.',
        howThisWorks: 'Upload the PDF, remove sticky notes and popups, then download the cleaned copy.',
        ctaText: 'Remove Sticky Notes',
        funnelTitle: 'Want a broader comments cleanup?',
        funnelBody: 'Open the PDF Comments & Markup Remover for general annotation cleanup, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/remove-pdf-comments', '/auditor'],
        relatedToolIds: ['comments-remover', 'metadata-stripper', 'hidden-text-remover'],
    }),
    createCommentsTool({
        id: 'remove-highlights-from-pdf',
        path: '/tools/remove-highlights-from-pdf',
        name: 'Remove Highlights from PDF',
        targetKeyword: 'remove highlights from pdf',
        headline: 'Delete highlighted markup from a PDF review copy.',
        description: 'Helpful when a review draft still shows highlight markup that should not be visible in the final file.',
        securityHero: 'Clear highlight markup before sending the final PDF.',
        subhead: 'Remove highlight annotations and related review markup from a PDF before it leaves your team.',
        primarySearchIntent: 'Remove highlights from PDF',
        metaTitle: 'Remove Highlights from PDF | Clean Review Markup',
        metaDescription: 'Remove highlight markup from a PDF in your browser before sharing a cleaned final copy.',
        focusTitle: 'Highlight Cleanup',
        focusText: 'Targets highlight-style annotations that often remain after review or approval rounds.',
        focusBullet: 'Removes highlighted markup while keeping the visible page content intact.',
        howThisWorks: 'Upload the PDF, remove highlight markup, and download the cleaned version.',
        ctaText: 'Remove Highlights',
        funnelTitle: 'Want broader annotation cleanup?',
        funnelBody: 'Open the PDF Comments & Markup Remover for broader cleanup, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/remove-pdf-comments', '/auditor'],
        relatedToolIds: ['comments-remover', 'metadata-stripper', 'hidden-text-remover'],
    }),
    createCommentsTool({
        id: 'remove-annotations-from-pdf',
        path: '/tools/remove-annotations-from-pdf',
        name: 'Remove Annotations from PDF',
        targetKeyword: 'remove annotations from pdf',
        headline: 'Delete PDF annotations such as notes, highlights, markup, and review layers.',
        description: 'A broad cleanup option for reviewed PDFs that still contain annotation objects.',
        securityHero: 'Remove annotation layers locally in your browser.',
        subhead: 'Clear common PDF annotations before sending the document to a client, counterparty, or regulator.',
        primarySearchIntent: 'Remove annotations from PDF',
        metaTitle: 'Remove Annotations from PDF | Clean PDF Review Layers',
        metaDescription: 'Remove annotations from a PDF in your browser before sharing a cleaned version.',
        focusTitle: 'Annotation Cleanup',
        focusText: 'Targets standard PDF annotations such as notes, highlights, free text, and popup replies.',
        focusBullet: 'Removes common annotation layers used by popular PDF editors.',
        howThisWorks: 'Upload the PDF, clear annotation objects, and download the cleaned copy.',
        ctaText: 'Remove Annotations',
        funnelTitle: 'Want a broader comments cleanup?',
        funnelBody: 'Open the PDF Comments & Markup Remover for broader annotation cleanup, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/remove-pdf-comments', '/auditor'],
        relatedToolIds: ['comments-remover', 'metadata-stripper', 'hidden-text-remover'],
    }),
    createCommentsTool({
        id: 'remove-apple-preview-comments-from-pdf',
        path: '/tools/remove-apple-preview-comments-from-pdf',
        name: 'Remove Apple Preview Comments from PDF',
        targetKeyword: 'remove apple preview comments from pdf',
        headline: 'Delete comments and markup left behind by Apple Preview.',
        description: 'Useful when a Mac Preview workflow leaves notes, highlights, or text boxes in the PDF.',
        securityHero: 'Clean Preview comments locally before sending the PDF.',
        subhead: 'Remove common comment and markup layers that often show up in PDFs edited with Apple Preview.',
        primarySearchIntent: 'Remove Apple Preview comments from PDF',
        metaTitle: 'Remove Apple Preview Comments from PDF',
        metaDescription: 'Remove Apple Preview comments and markup from a PDF in your browser before sharing it.',
        focusTitle: 'Preview Comment Cleanup',
        focusText: 'Targets the standard annotation structures used underneath many Preview comment workflows.',
        focusBullet: 'Useful for comment layers commonly added through Apple Preview.',
        howThisWorks: 'Upload the PDF, remove Preview-style comment layers, and download the cleaned copy.',
        ctaText: 'Remove Preview Comments',
        funnelTitle: 'Want broader annotation cleanup?',
        funnelBody: 'Open the PDF Comments & Markup Remover for broader annotation cleanup, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/remove-pdf-comments', '/auditor'],
        relatedToolIds: ['comments-remover', 'metadata-stripper', 'hidden-text-remover'],
    }),
    createCommentsTool({
        id: 'remove-adobe-comments-from-pdf',
        path: '/tools/remove-adobe-comments-from-pdf',
        name: 'Remove Adobe Comments from PDF',
        targetKeyword: 'remove adobe comments from pdf',
        headline: 'Delete comments, notes, and review markup left behind in Adobe-based workflows.',
        description: 'Helpful for Acrobat review copies that should be cleaned before the document is shared externally.',
        securityHero: 'Clear Acrobat-style comments before sending the PDF.',
        subhead: 'Remove common comment and review layers that often remain in PDFs edited with Adobe tools.',
        primarySearchIntent: 'Remove Adobe comments from PDF',
        metaTitle: 'Remove Adobe Comments from PDF | Clean Review Copy',
        metaDescription: 'Remove Adobe comments, notes, and review markup from a PDF in your browser before sharing it.',
        focusTitle: 'Adobe Comment Cleanup',
        focusText: 'Targets the annotation layers commonly used in Adobe review workflows.',
        focusBullet: 'Useful for cleaning comments and markup from Acrobat-reviewed PDFs.',
        howThisWorks: 'Upload the PDF, remove Adobe-style review layers, and download the cleaned copy.',
        ctaText: 'Remove Adobe Comments',
        funnelTitle: 'Want broader annotation cleanup?',
        funnelBody: 'Open the PDF Comments & Markup Remover for broader annotation cleanup, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/remove-pdf-comments', '/auditor'],
        relatedToolIds: ['comments-remover', 'metadata-stripper', 'hidden-text-remover'],
    }),
];

const hiddenTextTools = [
    createHiddenTextTool({
        id: 'hidden-text-remover',
        path: '/tools/remove-hidden-text',
        name: 'PDF Hidden Text Remover',
        targetKeyword: 'remove hidden text from pdf',
        headline: 'Flatten the PDF into a share-safe copy with hidden text removed.',
        description: 'Rebuilds each page as an image-based PDF so hidden text layers are much harder to recover casually.',
        securityHero: 'Destroy recoverable text layers locally in the browser.',
        subhead: 'Turn a risky PDF into a flattened, image-based copy that is easier to share safely.',
        primarySearchIntent: 'Remove hidden text from PDF',
        metaTitle: 'Remove Hidden Text from PDF | Flatten PDF in Browser',
        metaDescription: 'Remove hidden text from a PDF by flattening it into an image-based copy in your browser.',
        focusTitle: 'Hidden Text Defense',
        focusText: 'Flattens pages so covered text is no longer copy-pasteable in the original layered form.',
        focusBullet: 'Rasterizes each page so hidden text layers are no longer directly extractable.',
        howThisWorks: 'Upload the PDF, flatten every page into a new image-based PDF, and download the cleaned copy.',
        ctaText: 'Remove Hidden Text',
        funnelTitle: 'Want to double-check the flattened file?',
        funnelBody: 'Open the PDF Auditor if you want to review the flattened file for ghost text, exposed names, or metadata leaks.',
        funnelTargets: ['/auditor', '/'],
        relatedToolIds: ['metadata-stripper', 'comments-remover', 'form-flattener'],
        badge: 'Free Utility',
        h1: 'Remove Hidden Text from PDF',
        trustSignals: 'Flattened Output • Local Processing • Safer Sharing',
        downloadPrefix: 'hidden-text-removed',
    }),
    createHiddenTextTool({
        id: 'flatten-pdf-to-remove-hidden-text',
        path: '/tools/flatten-pdf-to-remove-hidden-text',
        name: 'Flatten PDF to Remove Hidden Text',
        targetKeyword: 'flatten pdf to remove hidden text',
        headline: 'Flatten the PDF into an image-based copy to reduce hidden text exposure.',
        description: 'Helpful when a PDF still contains selectable or recoverable text under visual redactions.',
        securityHero: 'Flatten pages locally before sharing the PDF.',
        subhead: 'Convert each page into an image-based PDF so the original layered text is no longer exposed in the same way.',
        primarySearchIntent: 'Flatten PDF to remove hidden text',
        metaTitle: 'Flatten PDF to Remove Hidden Text',
        metaDescription: 'Flatten a PDF in your browser to remove hidden text layers and create an image-based copy.',
        focusTitle: 'Flattened Output',
        focusText: 'Rebuilds the PDF into image-based pages that are easier to share safely.',
        focusBullet: 'Converts the PDF into a flattened, image-based copy.',
        howThisWorks: 'Upload the PDF, flatten the pages, and download the new image-based version.',
        ctaText: 'Flatten PDF',
        funnelTitle: 'Want the main flattening tool?',
        funnelBody: 'Open the PDF Hidden Text Remover for the main flattening workflow, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/remove-hidden-text', '/auditor'],
        relatedToolIds: ['hidden-text-remover', 'metadata-stripper', 'comments-remover'],
    }),
    createHiddenTextTool({
        id: 'make-pdf-non-searchable',
        path: '/tools/make-pdf-non-searchable',
        name: 'Make PDF Non-Searchable',
        targetKeyword: 'make pdf non searchable',
        headline: 'Convert a searchable PDF into an image-based version.',
        description: 'Useful when you want to remove live text layers and create a document that behaves more like a scan.',
        securityHero: 'Create a non-searchable PDF locally.',
        subhead: 'Flatten searchable text into an image-based PDF so the document is no longer searchable in the same way.',
        primarySearchIntent: 'Make PDF non-searchable',
        metaTitle: 'Make PDF Non-Searchable | Flatten Text Layers',
        metaDescription: 'Make a PDF non-searchable in your browser by converting it into an image-based copy.',
        focusTitle: 'Non-Searchable Output',
        focusText: 'Removes the live searchable text layer by flattening each page into an image.',
        focusBullet: 'Converts searchable PDFs into image-based files that are no longer searchable in the same way.',
        howThisWorks: 'Upload the PDF, flatten the pages, and download a non-searchable version.',
        ctaText: 'Make PDF Non-Searchable',
        funnelTitle: 'Need the full flattening tool?',
        funnelBody: 'Open the PDF Hidden Text Remover for the main flattening workflow, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/remove-hidden-text', '/auditor'],
        relatedToolIds: ['hidden-text-remover', 'metadata-stripper', 'comments-remover'],
    }),
    createHiddenTextTool({
        id: 'remove-selectable-text-from-pdf',
        path: '/tools/remove-selectable-text-from-pdf',
        name: 'Remove Selectable Text from PDF',
        targetKeyword: 'remove selectable text from pdf',
        headline: 'Flatten a PDF so the original selectable text layer is removed.',
        description: 'Useful when copied text still exposes content that should no longer be extractable in the original form.',
        securityHero: 'Remove selectable text locally before sharing.',
        subhead: 'Convert a layered PDF into an image-based copy so the original selectable text layer is no longer present.',
        primarySearchIntent: 'Remove selectable text from PDF',
        metaTitle: 'Remove Selectable Text from PDF | Flatten PDF',
        metaDescription: 'Remove selectable text from a PDF by flattening it into an image-based copy in your browser.',
        focusTitle: 'Selectable Text Cleanup',
        focusText: 'Rebuilds each page as an image so the original selectable text layer is no longer present.',
        focusBullet: 'Targets documents where selectable text still exposes content you do not want extractable.',
        howThisWorks: 'Upload the PDF, flatten its pages, and download the image-based copy.',
        ctaText: 'Remove Selectable Text',
        funnelTitle: 'Need the full flattening tool?',
        funnelBody: 'Open the PDF Hidden Text Remover for the main flattening workflow, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/remove-hidden-text', '/auditor'],
        relatedToolIds: ['hidden-text-remover', 'metadata-stripper', 'comments-remover'],
    }),
    createHiddenTextTool({
        id: 'burn-in-pdf-redactions',
        path: '/tools/burn-in-pdf-redactions',
        name: 'Burn In PDF Redactions',
        targetKeyword: 'burn in pdf redactions',
        headline: 'Flatten a PDF so visible redactions are burned into the final file.',
        description: 'Useful when you want the final PDF to behave more like a static image than a layered document.',
        securityHero: 'Burn visible redactions into the final PDF locally.',
        subhead: 'Flatten the PDF into an image-based copy so visible redactions become part of the final page image.',
        primarySearchIntent: 'Burn in PDF redactions',
        metaTitle: 'Burn In PDF Redactions | Flatten Redacted PDF',
        metaDescription: 'Burn redactions into a PDF by flattening it into an image-based copy in your browser.',
        focusTitle: 'Burn-In Output',
        focusText: 'Rebuilds the PDF into page images so visible redactions are part of the final output.',
        focusBullet: 'Creates a flattened copy where redactions are burned into the page image.',
        howThisWorks: 'Upload the PDF, flatten the pages, and download the burned-in version.',
        ctaText: 'Burn In Redactions',
        funnelTitle: 'Need the full flattening tool?',
        funnelBody: 'Open the PDF Hidden Text Remover for the main flattening workflow, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/remove-hidden-text', '/auditor'],
        relatedToolIds: ['hidden-text-remover', 'metadata-stripper', 'comments-remover'],
    }),
    createHiddenTextTool({
        id: 'convert-pdf-to-image-only',
        path: '/tools/convert-pdf-to-image-only',
        name: 'Convert PDF to Image-Only PDF',
        targetKeyword: 'convert pdf to image-only pdf',
        headline: 'Turn a layered PDF into an image-only PDF copy.',
        description: 'Useful when you want a static document that behaves more like a scan than an editable PDF.',
        securityHero: 'Convert PDFs to image-only files locally.',
        subhead: 'Flatten a layered PDF into an image-only version that is easier to share safely.',
        primarySearchIntent: 'Convert PDF to image-only PDF',
        metaTitle: 'Convert PDF to Image-Only PDF',
        metaDescription: 'Convert a PDF to an image-only PDF in your browser by flattening each page.',
        focusTitle: 'Image-Only Conversion',
        focusText: 'Turns the PDF into a static image-based document instead of a layered text PDF.',
        focusBullet: 'Creates an image-only PDF that behaves more like a scan.',
        howThisWorks: 'Upload the PDF, convert it into an image-only version, and download the result.',
        ctaText: 'Convert to Image-Only PDF',
        funnelTitle: 'Need the full flattening tool?',
        funnelBody: 'Open the PDF Hidden Text Remover for the main flattening workflow, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/remove-hidden-text', '/auditor'],
        relatedToolIds: ['hidden-text-remover', 'metadata-stripper', 'comments-remover'],
    }),
];

const piiTools = [
    createPiiTool({
        id: 'pii-scanner',
        path: '/tools/scan-pdf-for-pii',
        name: 'PDF PII Scanner',
        targetKeyword: 'find personal data in pdf',
        headline: 'Scan for dates, names, metadata, and redaction leak signals.',
        description: 'Uses the same underlying scanner logic as the Auditor to surface likely sensitive data exposure before a document is sent or published.',
        securityHero: 'Names, dates, and metadata are scanned locally only.',
        subhead: 'Quickly triage whether a PDF contains exposed names, dates, metadata, or risky redaction patterns before sending it to anyone else.',
        primarySearchIntent: 'Scan PDF for personal data',
        metaTitle: 'Scan PDF for PII | Find Personal Data in PDF',
        metaDescription: 'Scan a PDF for names, dates, metadata, and leak signals in your browser before sharing it.',
        focusTitle: 'PII Signals',
        focusText: 'Find dates, names, and document fingerprints in the text and metadata.',
        focusBullet: 'Surfaces names, dates, metadata traces, and ghost-text style leak signals.',
        howThisWorks: 'Upload your PDF, review counts and sample findings, then continue into a deeper review if needed.',
        ctaText: 'Scan for PII',
        funnelTitle: 'Want a deeper document review?',
        funnelBody: 'Open the PDF Auditor if you want a fuller review of names, dates, metadata, and hidden leak signals.',
        funnelTargets: ['/auditor', '/'],
        relatedToolIds: ['metadata-stripper', 'comments-remover', 'hidden-text-remover'],
        badge: 'Scan Tool',
        h1: 'Scan a PDF for PII and Hidden Leak Signals',
        trustSignals: 'Client-Side Scan • No Upload • Quick Review',
    }),
    createPiiTool({
        id: 'scan-pdf-for-personal-information',
        path: '/tools/scan-pdf-for-personal-information',
        name: 'Scan PDF for Personal Information',
        targetKeyword: 'scan pdf for personal information',
        headline: 'Check whether a PDF exposes names, dates, or other personal information.',
        description: 'Useful before sending a document externally when you want to catch obvious sensitive-data exposure first.',
        securityHero: 'Scan personal-information risk locally before sharing.',
        subhead: 'Review the PDF for likely names, dates, metadata, and other leak signals before the file leaves your control.',
        primarySearchIntent: 'Scan PDF for personal information',
        metaTitle: 'Scan PDF for Personal Information',
        metaDescription: 'Scan a PDF for personal information in your browser before emailing or uploading the file.',
        focusTitle: 'Personal Information Scan',
        focusText: 'Looks for names, dates, metadata, and other signals that can expose personal information.',
        focusBullet: 'Quickly scans for common personal-information signals before you share the document.',
        howThisWorks: 'Upload the PDF, review likely personal-information findings, and decide whether the file needs more cleanup.',
        ctaText: 'Scan Personal Information',
        funnelTitle: 'Need the full scanner page?',
        funnelBody: 'Open the PDF PII Scanner for the main scanning workflow, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/scan-pdf-for-pii', '/auditor'],
        relatedToolIds: ['pii-scanner', 'metadata-stripper', 'hidden-text-remover'],
    }),
    createPiiTool({
        id: 'find-names-in-pdf',
        path: '/tools/find-names-in-pdf',
        name: 'Find Names in PDF',
        targetKeyword: 'find names in pdf',
        headline: 'Scan a PDF for likely names and identity clues.',
        description: 'Helpful when you want to know whether a file still exposes names in text, metadata, or notes.',
        securityHero: 'Scan for names locally before sending the PDF.',
        subhead: 'Look for likely names and identifying text that still appears in the PDF before you share it externally.',
        primarySearchIntent: 'Find names in PDF',
        metaTitle: 'Find Names in PDF | Scan PDF for Names',
        metaDescription: 'Find names in a PDF by scanning the text and metadata in your browser before sharing the file.',
        focusTitle: 'Name Scan',
        focusText: 'Looks for likely names in the text, metadata, and common annotation content.',
        focusBullet: 'Highlights likely names that still appear in the PDF.',
        howThisWorks: 'Upload the PDF, scan for likely names, and review the results before sharing.',
        ctaText: 'Find Names',
        funnelTitle: 'Need the full scanner page?',
        funnelBody: 'Open the PDF PII Scanner for broader scanning, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/scan-pdf-for-pii', '/auditor'],
        relatedToolIds: ['pii-scanner', 'metadata-stripper', 'hidden-text-remover'],
    }),
    createPiiTool({
        id: 'find-dates-in-pdf',
        path: '/tools/find-dates-in-pdf',
        name: 'Find Dates in PDF',
        targetKeyword: 'find dates in pdf',
        headline: 'Scan a PDF for dates that may still expose timing or personal details.',
        description: 'Useful when dates, birth dates, settlement dates, or filing dates may still be visible in the file.',
        securityHero: 'Scan date exposure locally before sharing the PDF.',
        subhead: 'Look for dates and date-like strings that still appear in the PDF before you email or upload the file.',
        primarySearchIntent: 'Find dates in PDF',
        metaTitle: 'Find Dates in PDF | Scan PDF for Dates',
        metaDescription: 'Find dates in a PDF by scanning the text and metadata in your browser before sharing the document.',
        focusTitle: 'Date Scan',
        focusText: 'Looks for date-like strings in the text and related document metadata.',
        focusBullet: 'Highlights dates that may still be visible in the PDF.',
        howThisWorks: 'Upload the PDF, scan for dates, and review the results before sharing the file.',
        ctaText: 'Find Dates',
        funnelTitle: 'Need the full scanner page?',
        funnelBody: 'Open the PDF PII Scanner for broader scanning, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/scan-pdf-for-pii', '/auditor'],
        relatedToolIds: ['pii-scanner', 'metadata-stripper', 'hidden-text-remover'],
    }),
    createPiiTool({
        id: 'check-pdf-for-hidden-sensitive-data',
        path: '/tools/check-pdf-for-hidden-sensitive-data',
        name: 'Check PDF for Hidden Sensitive Data',
        targetKeyword: 'check pdf for hidden sensitive data',
        headline: 'Scan a PDF for names, dates, metadata, and other hidden sensitive-data signals.',
        description: 'Helpful before a document is sent outside your team or organization.',
        securityHero: 'Check hidden sensitive-data risk locally before sharing.',
        subhead: 'Review the PDF for likely hidden sensitive-data signals before you send the file externally.',
        primarySearchIntent: 'Check PDF for hidden sensitive data',
        metaTitle: 'Check PDF for Hidden Sensitive Data',
        metaDescription: 'Check a PDF for hidden sensitive data in your browser before sharing the document.',
        focusTitle: 'Sensitive-Data Scan',
        focusText: 'Looks for names, dates, metadata, and ghost-text style leak signals.',
        focusBullet: 'Scans for hidden sensitive-data signals before the PDF leaves your control.',
        howThisWorks: 'Upload the PDF, scan for hidden sensitive-data signals, and review the findings.',
        ctaText: 'Check Sensitive Data',
        funnelTitle: 'Need the full scanner page?',
        funnelBody: 'Open the PDF PII Scanner for broader scanning, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/scan-pdf-for-pii', '/auditor'],
        relatedToolIds: ['pii-scanner', 'metadata-stripper', 'hidden-text-remover'],
    }),
];

const formTools = [
    createFormTool({
        id: 'form-flattener',
        path: '/tools/flatten-fillable-pdf',
        name: 'PDF Form Field & Signature Flattener',
        targetKeyword: 'flatten fillable pdf',
        headline: 'Flatten fillable fields before you send the final PDF out.',
        description: 'Converts interactive form fields into static page content so recipients cannot casually edit the filled responses.',
        securityHero: 'Turn editable fields into a static final copy.',
        subhead: 'Flatten interactive form fields before sharing applications, contracts, disclosures, or signed documents externally.',
        primarySearchIntent: 'Flatten fillable PDF form',
        metaTitle: 'Flatten Fillable PDF | PDF Form Field Flattener',
        metaDescription: 'Flatten a fillable PDF into a static copy in your browser before sharing the final document.',
        focusTitle: 'Field Flattening',
        focusText: 'Turns live form fields into fixed page content so the PDF behaves like a finalized document.',
        focusBullet: 'Flattens editable AcroForm fields into fixed page content.',
        howThisWorks: 'Upload the PDF, flatten live form fields, and download the static version.',
        ctaText: 'Flatten PDF Form',
        funnelTitle: 'Need a deeper document review?',
        funnelBody: 'Open the PDF Auditor if you want to check the flattened PDF for metadata, hidden annotation text, or other leak signals.',
        funnelTargets: ['/auditor', '/'],
        relatedToolIds: ['metadata-stripper', 'comments-remover', 'hidden-text-remover'],
        badge: 'Workflow Utility',
        h1: 'Flatten a Fillable PDF',
        trustSignals: 'Static Output • Local Only • Document Finalization',
        downloadPrefix: 'form-flattened',
    }),
    createFormTool({
        id: 'flatten-signed-pdf',
        path: '/tools/flatten-signed-pdf',
        name: 'Flatten Signed PDF',
        targetKeyword: 'flatten signed pdf',
        headline: 'Flatten a signed PDF into a more static final copy.',
        description: 'Useful when a signed packet still contains editable fields or form controls that should be locked down before sharing.',
        securityHero: 'Flatten signed PDF packets locally before sending.',
        subhead: 'Turn a signed PDF with live fields into a more static final copy that is easier to share externally.',
        primarySearchIntent: 'Flatten signed PDF',
        metaTitle: 'Flatten Signed PDF | Finalize Signed Packet',
        metaDescription: 'Flatten a signed PDF in your browser before sending the final packet externally.',
        focusTitle: 'Signed Packet Finalization',
        focusText: 'Flattens remaining live fields in a signed packet so the final PDF is easier to share.',
        focusBullet: 'Useful for signed PDFs that still contain editable form fields.',
        howThisWorks: 'Upload the signed PDF, flatten remaining live fields, and download the finalized copy.',
        ctaText: 'Flatten Signed PDF',
        funnelTitle: 'Need the main form tool?',
        funnelBody: 'Open the PDF Form Flattener for the main form workflow, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/flatten-fillable-pdf', '/auditor'],
        relatedToolIds: ['form-flattener', 'metadata-stripper', 'hidden-text-remover'],
    }),
    createFormTool({
        id: 'lock-pdf-form-fields',
        path: '/tools/lock-pdf-form-fields',
        name: 'Lock PDF Form Fields',
        targetKeyword: 'lock pdf form fields',
        headline: 'Flatten form fields so the PDF behaves like a locked final copy.',
        description: 'Helpful when completed forms should no longer be casually editable by recipients.',
        securityHero: 'Lock form-style PDFs locally before sharing.',
        subhead: 'Flatten form fields so recipients receive a more static PDF instead of an editable working file.',
        primarySearchIntent: 'Lock PDF form fields',
        metaTitle: 'Lock PDF Form Fields | Flatten Completed Form',
        metaDescription: 'Lock PDF form fields by flattening them into a static copy in your browser.',
        focusTitle: 'Field Locking',
        focusText: 'Turns live form controls into fixed page content so the file behaves more like a final copy.',
        focusBullet: 'Locks form-style PDFs by flattening interactive fields.',
        howThisWorks: 'Upload the PDF, flatten its live form fields, and download the updated copy.',
        ctaText: 'Lock Form Fields',
        funnelTitle: 'Need the main form tool?',
        funnelBody: 'Open the PDF Form Flattener for the main form workflow, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/flatten-fillable-pdf', '/auditor'],
        relatedToolIds: ['form-flattener', 'metadata-stripper', 'hidden-text-remover'],
    }),
    createFormTool({
        id: 'make-fillable-pdf-read-only',
        path: '/tools/make-fillable-pdf-read-only',
        name: 'Make Fillable PDF Read Only',
        targetKeyword: 'make fillable pdf read only',
        headline: 'Flatten a fillable PDF so it behaves like a read-only document.',
        description: 'Helpful for forms that are complete and should now be shared as a final static copy.',
        securityHero: 'Create a read-only style PDF locally.',
        subhead: 'Turn a fillable PDF into a more static document by flattening the live form fields before sharing.',
        primarySearchIntent: 'Make fillable PDF read only',
        metaTitle: 'Make Fillable PDF Read Only | Flatten Form',
        metaDescription: 'Make a fillable PDF read only by flattening its fields in your browser.',
        focusTitle: 'Read-Only Style Output',
        focusText: 'Flattens the live form layer so the file behaves more like a static document.',
        focusBullet: 'Turns fillable PDFs into more read-only style final copies.',
        howThisWorks: 'Upload the PDF, flatten the fields, and download the more static version.',
        ctaText: 'Make Read Only',
        funnelTitle: 'Need the main form tool?',
        funnelBody: 'Open the PDF Form Flattener for the main form workflow, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/flatten-fillable-pdf', '/auditor'],
        relatedToolIds: ['form-flattener', 'metadata-stripper', 'hidden-text-remover'],
    }),
    createFormTool({
        id: 'remove-editable-fields-from-pdf',
        path: '/tools/remove-editable-fields-from-pdf',
        name: 'Remove Editable Fields from PDF',
        targetKeyword: 'remove editable fields from pdf',
        headline: 'Flatten editable fields so the final PDF no longer behaves like a form.',
        description: 'Useful for completed application packets, onboarding forms, and contracts that should be sent as final copies.',
        securityHero: 'Remove editable fields locally before sending the PDF.',
        subhead: 'Turn editable fields into fixed page content so the PDF is easier to share as a final document.',
        primarySearchIntent: 'Remove editable fields from PDF',
        metaTitle: 'Remove Editable Fields from PDF | Flatten Form',
        metaDescription: 'Remove editable fields from a PDF by flattening them into a static copy in your browser.',
        focusTitle: 'Editable Field Removal',
        focusText: 'Flattens editable fields so the final document no longer behaves like a live form.',
        focusBullet: 'Useful when you want a completed PDF to stop behaving like an editable form.',
        howThisWorks: 'Upload the PDF, flatten editable fields, and download the final copy.',
        ctaText: 'Remove Editable Fields',
        funnelTitle: 'Need the main form tool?',
        funnelBody: 'Open the PDF Form Flattener for the main form workflow, or continue to the PDF Auditor for a deeper review.',
        funnelTargets: ['/tools/flatten-fillable-pdf', '/auditor'],
        relatedToolIds: ['form-flattener', 'metadata-stripper', 'hidden-text-remover'],
    }),
];

export const PDF_TOOLS: PdfToolDefinition[] = [
    ...metadataTools,
    ...commentsTools,
    ...hiddenTextTools,
    ...piiTools,
    ...formTools,
];

export const PDF_TOOL_MAP = Object.fromEntries(PDF_TOOLS.map((tool) => [tool.path, tool])) as Record<string, PdfToolDefinition>;

export const PDF_TOOL_ROUTE_CONFIG = Object.fromEntries(
    PDF_TOOLS.map((tool) => [tool.path, tool.routeConfig]),
) as Record<string, RouteConfig>;

export function getPdfToolByPath(pathname: string): PdfToolDefinition | undefined {
    const normalizedPath = pathname === '/' ? pathname : pathname.replace(/\/+$/, '');
    return PDF_TOOL_MAP[normalizedPath];
}

export function getPdfToolById(id: PdfToolId): PdfToolDefinition | undefined {
    return PDF_TOOLS.find((tool) => tool.id === id);
}
